# Generated by Django 5.1.5 on 2025-01-24 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscripcionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Plan')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Subscripción',
                'verbose_name_plural': 'Subscripciones',
                'db_table': 'subscripciones',
            },
        ),
        migrations.CreateModel(
            name='UsuarioDb',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('nombre_de_usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='PedidoDb',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estado_pedido', models.CharField(max_length=20, verbose_name='Estado del Pedido')),
                ('estado_pago', models.CharField(max_length=20, verbose_name='Estado del Pago')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuariodb', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
    ]
