# Generated by Django 5.1.5 on 2025-01-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripciondb',
            name='usuario_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuariodb', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
