# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_subscripciondb_usuario_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodb',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('CL', 'Común'), ('AD', 'Administrador')], default='CL', max_length=13),
        ),
    ]
