# Generated by Django 5.1.5 on 2025-02-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
    ]
