# Generated by Django 5.1.5 on 2025-01-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
