# Generated by Django 5.1.5 on 2025-01-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suscripciones', '0003_delete_suscripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscripcionCliente',
            new_name='Subscripcion',
        ),
    ]
