# Generated by Django 5.1.5 on 2025-01-29 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(default=1, max_length=255, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default=1, max_length=15, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estado_pedido', models.CharField(max_length=20, verbose_name='Estado del Pedido')),
                ('estado_pago', models.CharField(max_length=20, verbose_name='Estado del Pago')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='SubscripcionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de Plan')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Subscripción',
                'verbose_name_plural': 'Subscripciones',
                'db_table': 'subscripciones',
            },
        ),
    ]
