# Generated by Django 5.1.5 on 2025-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRP', '0002_customuser_apellido_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
    ]
