# Generated by Django 5.1.5 on 2025-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('tipo_servicio', models.TextField(max_length=1000, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado del Pedido')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado')], max_length=20, verbose_name='Estado del Pago')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
    ]
