# Generated by Django 5.1.5 on 2025-01-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
