# Generated by Django 5.1.5 on 2025-02-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_pedido_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('listo', 'Listo'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
